config/routes.rb
Rails.application.routes.draw do
  # resources :discussions
  root 'discussions#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      resources :discussions do
        collection do
          post 'user_post'
          post 'follow_user'
          get 'all_discussion'
          get 'my_post'
          post 'submit_comment'
        end 
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :discussion
end

app/models/discussion.rb
class Discussion < ApplicationRecord
    belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :discussions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :verify_parameter , if: :devise_controller?

    protected
    
    def verify_parameter
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])

    end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  layout 'dashboard'
  before_action :authenticate_user!
  before_action :set_discussion, only: %i[ show edit update destroy ]

  # GET /discussions or /discussions.json
  def index
    follow = Follow.where(:sessionuser=>current_user.id)
    @discussions = (Discussion.all.where(:user_id=>current_user.id)+Discussion.where(:user_id=>follow.pluck(:user_id))).uniq
  end

  def all_discussion
    if params[:q].present?
      user= User.where('name LIKE ?',"#{params[:q]}%")
      @discussions = Discussion.all.where(:user_id=>user.pluck(:id))
    else
      @discussions = Discussion.all
    end
  end

  def my_post
    @discussions = Discussion.all.where(:user_id=>current_user.id)
  end

  # GET /discussions/1 or /discussions/1.json
  def show
  end

  def submit_comment
    discussion = Discussion.find(params[:id])
    Comment.create(:comment=>params[:uname],:discussion_id=>params[:id], :user_id=>current_user.id)
    respond_to do |format|
      format.html { redirect_to discussion, notice: " successfully commented" }
      format.json { head :no_content }
    end
  end

  def user_post
     @user_id = params[:id]
     @discussions = Discussion.all.where(:user_id=>@user_id)
  end

  def follow_user
     user_id = params[:id]
     Follow.create(:user_id=>user_id,:sessionuser=>current_user.id)
     respond_to do |format|
      format.html { redirect_to discussions_url, notice: "Discussion was successfully followed" }
      format.json { head :no_content }
    end
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions or /discussions.json
  def create
    @discussion = Discussion.new(discussion_params)
    @discussion.user_id = current_user.id

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: "Discussion was successfully created." }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1 or /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: "Discussion was successfully updated." }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1 or /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: "Discussion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def discussion_params
      params.require(:discussion).permit(:description, :topic)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= form_with(model: discussion, local: true) do |form| %>
  <% if discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
        <% discussion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :topic %>
    <%= form.select :topic,['topic1','topic2','topic3','topic4','topic5'] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/discussions/all_discussion.html.erb
<p id="notice"><%= notice %></p>

<%= form_for discussions_path, method: :get do |f| %>
    <%= text_field_tag :q , params[:q] %>
    <%= submit_tag "Go" %> 
    <% end %>
<table>
  <thead>
    <tr>
    <th>Author</th>
      <th>Description</th>
      <th>Topic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discussions.each do |discussion| %>
      <tr>
      <td><%= link_to "#{User.find(discussion.user_id).name}" ,{:controller=>'discussions',:action=>'user_post',:id=>discussion.user_id},:method=>:post %></td>
        <td><%= discussion.description %></td>
        <td><%= discussion.topic %></td>
        <td><%= link_to 'Show', discussion %></td>
      </tr>
    <% end %>
  </tbody>
</table>


app/views/discussions/edit.html.erb
<h1>Editing Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
    <th>Author</th>
      <th>Description</th>
      <th>Topic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discussions.each do |discussion| %>
      <tr>
      <td><%= link_to "#{User.find(discussion.user_id).name}" ,{:controller=>'discussions',:action=>'user_post',:id=>discussion.user_id},:method=>:post %></td>
        <td><%= discussion.description %></td>
        <td><%= discussion.topic %></td>
        <td><%= link_to 'Show', discussion %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/discussions/my_post.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Topic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discussions.each do |discussion| %>
      <tr>
        <td><%= discussion.description %></td>
        <td><%= discussion.topic %></td>
        <td><%= link_to 'Show', discussion %></td>
        <td><%= link_to 'Edit', edit_discussion_path(discussion) %></td>
        <td><%= link_to 'Destroy', discussion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


app/views/discussions/new.html.erb
<h1>New Discussion</h1>

<%= render 'form', discussion: @discussion %>

app/views/discussions/show.html.erb
<p id="notice"><%= notice %></p>
<h3><%= "Author : #{(User.find(@discussion.user_id)).name}" %></h3>
<p>
  <strong>Description:</strong>
  <%= @discussion.description %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @discussion.topic %>
</p>


<% Comment.all.each do |comment| %>
  <p>
  <%="#{User.find(comment.user_id).name} commented on #{comment.created_at.strftime("%B %e,%Y")}"  %>
  <%= (comment.comment).html_safe %></p>
<%end%>

<form action="/users/discussions/submit_comment" method="post" >
<%= hidden_field_tag :authenticity_token ,form_authenticity_token %>
<%= hidden_field_tag :id ,@discussion.id %>
<label for="uname">Add Comment</label>
<input type="text" placeholder="Enter Comment" name="uname" required>
<button type="submit">Comment</button>
</form>

app/views/discussions/user_post.html.erb
<p id="notice"><%= notice %></p>
<h3><%=" Author :#{User.find(@user_id).name}"%></h3>
<% follow = Follow.find_by(:user_id=>@user_id )%>
<% if follow.present? %>
   <h3> Followed </h3>
<%else%>
  <h3><%= link_to "Follow" ,{:controller=>'discussions',:action=>'follow_user',:id=>@user_id},:method=>:post %></h3>
<%end%>
  <table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Topic</th>
    </tr>
  </thead>

  <tbody>
    <% @discussions.each do |discussion| %>
      <tr>
        <td><%= discussion.description %></td>
        <td><%= discussion.topic %></td>
      </tr>
    <% end %>
  </tbody>
</table>


app/views/layouts/_header.html.erb
<html>
  <head>
    <meta name="viewpot", content="width=devise-width initial-scale=1">
    <style>
    body {
        margin: 0;
        font-family: Arial,Helvetica,sans-serif;
    }
    .topnav {
        overflow: hidden;
        background-color: #333;
    }
    .topnav a {
        float: left;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
    }
    </style>
  </head>

  <body>
    <div class="topnav">
    <a href="<%= root_url %>">Home</a>
    <a href="<%= new_discussion_path %>">Add Discussion</a>
    <%= link_to 'My Posts', my_post_discussions_path %>
     <%= link_to 'All Discussion', all_discussion_discussions_path %>
    <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>

    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webchat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<html>
  <head>
    <title>Webchat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: 'layouts/header' %>
    <%= yield %>
  </body>
</html>